---
version: 2
jobs:
  frontend_build_test:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/cyf-react
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-dependencies-{{ checksum "frontend/yarn.lock" }}
      - setup_remote_docker
      - run:
          name: Install dependencies for lint and test
          command: cd frontend && yarn
      - run:
          name: Lint project & run test
          command: yarn lint && yarn test
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:
          name: Docker build frontend
          command: docker build -t codeyourfuture/cyf-react-fe:$VERSION --build-arg version=$VERSION docker tag codeyourfuture/cyf-react-fe:$VERSION codeyourfuture/cyf-react-fe:latest
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker push frontend
          command: docker push codeyourfuture/directory-of-services-fe
  deploy_staging:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x kubectl
      - run:
          name: Install gnupg
          command: sudo apt-get -y install gnupg
      - run:
          name: Get kubeconfig
          command: aws s3 cp s3://$SECRETS_BUCKET/kubectl/config_cyfbot_staging.gpg ./config.gpg
      - run:
          name: Decrypt kubeconfig and set KUBECONFIG
          command: gpg --yes --passphrase="$GPG_KEY" config.gpg
      - run:
          name: Update k8s deployments
          command: |
            KUBECONFIG=$(pwd)/config ./kubectl -n staging set image deployment/cyf-react-dep-fe cyf-react-fe=codeyourfuture/cyf-react-fe:$VERSION

workflows:
  version: 2
  build_and_test:
    jobs:
      - frontend_build_test:
          context: build
      - deploy_staging:
          context: deployments_staging
          requires:
            - frontend_build_test
          filters:
            branches:
              only:
                - staging
